const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const ctx=vm.createContext({window:{},Intl});
for(const f of ['programs.js','estimates.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),ctx);
vm.runInContext(fs.readFileSync('dist/app.js','utf8').split('filterIds.forEach(k=>')[0],ctx);
const {investment,training}=ctx.window.FundingEstimates;
const inv={route:'general',cost:1e7,people:20,eligible:true};
const tr={size:'sme',content:'job',format:'live',people:10,hours:20,fee:300000,eligible:true,annualUsed:0};
const calc={coreCount:0,coreSalary:500,newCount:10,wage:1200,calcHours:30,burden:15,otherCost:500,startup:700,revenue:3500,grantCount:10,grant:'trial',size:'sme',criteria:true,receiptYear:'1'};
const call=(fn,...args)=>{ctx.args=args;return vm.runInContext(fn+'(...args)',ctx)};
test('資格未確認の投資・研修は金額を確定しない',()=>{assert.equal(investment({...inv,eligible:false}).amount,null);assert.equal(training({...tr,size:'unknown'}).amount,null);assert.equal(training({...tr,eligible:false}).amount,null)});
test('投資額・人数・賃上げで結果が変わり上限で止まる',()=>{assert.equal(investment(inv).amount,5000000);assert.equal(investment({...inv,cost:4e7}).amount,15000000);assert.equal(investment({...inv,cost:4e7,people:5}).amount,7500000);assert.equal(investment({...inv,cost:4e7,people:5,raise:true}).amount,10000000)});
test('通常枠の150万円未満と4プロセスの上限を区別',()=>{assert.equal(investment({...inv,route:'normal'}).amount,1499999);assert.equal(investment({...inv,route:'normal',processes:'four'}).amount,4500000)});
test('新事業の補助下限と一般型の最低投資を満たさなければ0',()=>{assert.equal(investment({...inv,route:'newbusiness'}).amount,0);assert.equal(investment({...inv,cost:499999}).amount,0)});
test('カタログの2026年3月以降の上限を使用',()=>assert.equal(investment({...inv,route:'catalog',cost:4e7,people:5}).amount,5000000));
test('通学・eラーニング・企業規模を区別',()=>{assert.equal(training(tr).amount,2450000);assert.equal(training({...tr,format:'elearning'}).amount,1500000);assert.equal(training({...tr,format:'elearning',size:'large'}).amount,1000000)});
test('汎用AI研修・10時間未満は0',()=>{assert.equal(training({...tr,content:'generic'}).amount,0);assert.equal(training({...tr,hours:9}).amount,0)});
test('年度上限1億と他の既支給額を反映',()=>{assert.equal(training({...tr,people:1000}).amount,100000000);const r=training({...tr,annualUsed:99900000});assert.equal(r.amount,100000);assert.equal(r.expense+r.wage-r.reduction,r.amount);assert.equal(training({...tr,annualUsed:1e8}).amount,0)});
test('負数・欠損・人数の小数は停止',()=>{assert.ok(training({...tr,annualUsed:-1}).error);assert.ok(training({...tr,hours:NaN}).error);assert.ok(investment({...inv,people:1.5}).error)});
test('全28枠の出典と用途を保持し、受付前・終了を現在受付に混ぜない',()=>{assert.equal(ctx.window.PROGRAMS.length,28);for(const p of ctx.window.PROGRAMS){assert.ok(p.sourceUrls.length);assert.ok(p.proposal);assert.ok(p.roles.length)}const r=call('matching',{perspective:'all',actor:'all',purpose:'all',availability:'current'});assert.ok(r.length);assert.ok(r.every(x=>['open','current'].includes(x.p.status)))});
test('大企業支配の除外入力を反映し、自社の適格性は断定しない',()=>{const p=ctx.window.PROGRAMS.find(x=>x.id==='private-digital-ai-2026-normal');assert.equal(call('assess',p,{perspective:'customer',size:'sme',ownership:'controlled'}).state,'blocked');assert.equal(call('assess',p,{perspective:'customer',size:'sme',ownership:'independent'}).state,'candidate');assert.equal(call('assess',p,{perspective:'self',size:'sme',ownership:'independent'}).state,'review')});
test('雇用助成は条件未確認・短時間では算入しない',()=>{assert.equal(call('calculate',{...calc,criteria:false}).grant,0);assert.equal(call('calculate',{...calc,calcHours:15}).grant,0)});
test('雇用助成は入金年のみ1回計上、入金不明なら計上しない',()=>{const r=call('calculate',calc);assert.equal(r.grant,1200000);assert.deepEqual(Array.from(r.receipts),[1200000,0,0]);assert.deepEqual(Array.from(call('calculate',{...calc,receiptYear:'2'}).receipts),[0,1200000,0]);assert.equal(call('calculate',{...calc,receiptYear:'unknown'}).grantAllocated,0)});
